version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./auth-backed-spring
    container_name: auth-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:p/     fdreeostgresql://db:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  frontend:
    build: ./auth-frontend-angular
    container_name: auth-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
